name: transformer_m3
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
    - colorama==0.4.6
    - filelock==3.17.0
    - fsspec==2025.2.0
    - jinja2==3.1.5
    - lxml==5.3.1
    - markupsafe==3.0.2
    - mpmath==1.3.0
    - networkx==3.4.2
    - numpy==2.2.3
    - pillow==11.1.0
    - portalocker==3.1.1
    - regex==2024.11.6
    - sacrebleu==2.5.1
    - sentencepiece==0.2.0
    - sympy==1.13.1
    - tabulate==0.9.0
    - torch==2.6.0
    - torchaudio==2.6.0
    - torchvision==0.21.0
    - tqdm==4.67.1
    - typing-extensions==4.12.2
